project-includes = [
    "backend",
]
project-excludes = [
    "**/node_modules",
    "**/__pycache__",
    "**/.venv",
    "**/__pyrefly_virtual__/**",
    "**/inmemory/**",
]
search-path = [
    "backend",
]
