project-includes = [
    "backend",
    "sdk/python",
    "cli",
]
project-excludes = [
    "**/node_modules",
    "**/__pycache__",
    "**/.venv",
    "**/__pyrefly_virtual__/**",
    "**/inmemory/**",
]
search-path = [
    "backend",
    "sdk/python",
    "cli",
]
